### ISSUE TITLE
Implement SQL Preview webview deserialize to show it after VSCode reload

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#102]
Currently, if you reload VSCode with PRQL editor and SQL Preview open, we get blank panel on the side where SQL Preview was before vscode reload. This happens because SQL Preview webview doesn't implement `deserialize`. Can be handled as part of #60.

See docs for more info: https://code.visualstudio.com/api/references/vscode-api#window.registerWebviewPanelSerializer

Sample implementation of that interface: https://github.com/RandomFractals/tabular-data-viewer/blob/main/src/views/tableViewSerializer.ts

![prql-sql-preview-reload](https://user-images.githubusercontent.com/656833/219388310-9afcc6d4-33a1-4f59-93c6-228c5f181252.png)

**Comment by max-sixty** [comment]
Great observation! This is the sort of issue that solving would demonstrate that some deep quality.
