### ISSUE TITLE
Add boolean prql.addTargetDialectToSqlFilenames setting for the generated SQL filenames

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#103]
to enable users targeting different DBMS systems to create `.sql` files with the target db/platform filename suffix.

 For example, sql file generated from some `invoices-total.prql` for the `duckdb` target will be named `invoices-total.duckdb.sql`. 

The same user can then change `prql.target` to `SQLite`, create and save somewhat different `invoices-total.sqlite.sql` file and add it to their project version control system.

In both scenarios we just add sql dialect suffix before `.sql` file extension name when generating sql files via #42 feature.

To keep it simple, we'll default this setting to `false`, and advanced users can change it in their workspace settings.

**Note:** we'll do this for all the supported SQL system dialects, and skip adding this sql filename suffix when the current workspace `prql.target` setting is `Generic` or `None` recently added in #98.

**Comment by RandomFractals** [comment]
Example of using this new setting:

![multi-target-sql-files](https://user-images.githubusercontent.com/656833/219420021-60cdd82e-116e-403f-a331-3282458d1bd7.png)

**Comment by max-sixty** [comment]
My guess is that this won't be used _that_ much — folks generally have a single DB they're working with. But no harm in adding 

(does VSCode share any telemetry so we can see who is using what settings?)

**Comment by RandomFractals** [comment]
I can see folks using some transactional db and duckdb for analytics use this feature in some form or the other. 

We can set up telemetry later. I don't think we have enough active users to start logging what features are used, or how many times sql preview is shown.

VSCode does have standard telemetry api, but that might require setting up Azure service, or do it with google analytics. i.e. much larger want/ask that should be written down as a separate ticket for us to consider adding it.
