### ISSUE TITLE
Display virtual sql filename in clipboard copy notification message

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#109]
This UI enhancement has been added to the new sql preview branch and will be merged soon.

See new copied to clipboard notification message below.

![prql-sql-filename-in-clipboard-info-msg](https://user-images.githubusercontent.com/656833/219955393-4889ff3d-ee81-4a6c-be76-89a88cb91e65.png)

**Comment by max-sixty** [comment]
The clipboard notification with the ID is underrated, very nice idea

**Comment by RandomFractals** [comment]
tbh, I added it to test if I copy content from the right doc without pasting into a new doc. Then I liked it and figured why not keep it. Tells what content it copied.
