### ISSUE TITLE
Syncing vscode extension version number with PRQL compiler releases

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql-vscode#142]
When the VS Code extension came out with the 0.5.2 PRQL compiler, the extension's version number was "0.6.0". Now that PRQL is at 0.6.0, there'll be a new VS Code extension. 

But what should its version number be? And should we try to keep it in sync with the PRQL compiler?

- It's convenient (low "cognitive load") to have them numbered the same 
- But it locks changes to the Extension to updates in the compiler

Does it matter? Or should we simply agree they should be separate? (For example, declare VSCode Extension to be 1.0 soon, then note that 1.0.1 has PRQL compiler 0.6.0, and extension 1.0.2 has new feature `foo` and PRQL compiler 0.6.0, and extension 1.0.3 has PRQL compiler 0.6.1, etc.) Thanks.

PS If this sets off a whole lot of work, just close this issue.

**Comment by max-sixty** [comment]
I agree! We had a short discussion on Discord about this.

I was a +0.1 on syncing the minor versions, I think @RandomFractals was keener for `prql-vscode` to not be inhibited, and he has been doing the work, so he gets to decide. Depending on how we go, it's not impossible to get them in sync again.

We should sync the major versions though, or at least I don't yet see a good reason to un-sync them.

@RandomFractals lmk if you have any thoughts, otherwise we can close...

**Comment by RandomFractals** [comment]
yes, I brought this up when packaging v0.6 with the multi-Sql preview updates.

https://discord.com/channels/936728116712316989/1028380004226171032/1077224905730437160

![prql-vscode-ext-version-discord-discussion-1](https://user-images.githubusercontent.com/656833/224691285-f66dfef1-05c1-4a9a-8816-a5c187be1ee0.png)

@max-sixty follow-up on that in dicsord:

https://discord.com/channels/936728116712316989/1028380004226171032/1077349146127769641

![prql-vscode-ext-version-discord-discussion-2](https://user-images.githubusercontent.com/656833/224691474-3cd080b8-9d6e-499b-9fa5-cc6a731e19a8.png)

I would like to create ext. version 1.x.x. I think it's mature enough, but we can keep it at 0.x for now.

Realistically, as stated in that discord discussion, keeping ext. version in sync with prql compiler might be logically tempting, but harder to maintain as ext. will be getting less updates now after that 0.6.0 release and prql compiler can iterate more to flash out prql language design, or vice versa if we need to add more UX features.

**Comment by richb-hanover** [comment]
@RandomFractals Updated the review. I also approve of the plan to let the VS Code extension and PRQL version numbers drift as needed. Thanks!
