### ISSUE TITLE
Update prql-js dependency to v0.6.1 to use new case, loop and other added PRQL compiler features

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#150]
See PRQL v0.6.0 and 0.6.1 release notes that list prql compiler lib updates: https://github.com/PRQL/prql/releases

Use new Pi PRQL example to test and demo it: https://prql-lang.org/posts/2023-03-14-pi-day/

**Comment by RandomFractals** [comment]
PRQL loop examples to test prql-js v0.6.1 update:

![image](https://user-images.githubusercontent.com/656833/225130537-7c92c8c5-f23b-4e6e-901d-ce73358f35f5.png)

**Comment by RandomFractals** [comment]
PRQL loop examples after `prql-js` update:

![image](https://user-images.githubusercontent.com/656833/225132269-18aedd29-6dea-479f-a100-13e34b45ab21.png)

**Comment by max-sixty** [comment]
Awesome @RandomFractals !

**Comment by RandomFractals** [comment]
Tested generates sql "loop" queries with duckdb sql tools in vscode:

![Uploading prql-duckdb-sql-tools-loop-tests.gif…]()

**Comment by RandomFractals** [comment]
Released: https://github.com/PRQL/prql-vscode/releases/tag/0.6.1
