### ISSUE TITLE
Badges not working

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql-vscode#245]
These seem to have reverted to text:

We can remove them unless we can fix them...

<img width="672" alt="image" src="https://github.com/PRQL/prql-vscode/assets/5635139/10075ced-78c9-4aba-846d-d5a544221674">

**Comment by RandomFractals** [comment]
@max-sixty Those VS Code badges were added in #87 to get more info about your extension installs and updates (downloads total). We find them useful to view those stats on github and in the extension info view in VS Code and on VS Code marketplace extension landing page.

You can resolve this issue by switching to using shields.io service directly, as Microsoft hosted https://vsmarketplacebadges.dev/ doesn't seem to work anymore. See example for that update in our geo data viewer repo: https://github.com/RandomFractals/geo-data-viewer/issues/146

Also, the full list of approved VS Code extension badges and trusted services is posted in this doc: https://code.visualstudio.com/api/references/extension-manifest#approved-badges

**Comment by RandomFractals** [comment]
Looks like this has been resolved in marketplace recently. Potentially by the marketplace dev team as many extensions use the vsmarketplacebadges.dev and did not switch to shilds.io for those stats. So, I suspect marketplace team redeployed that server. 

![image](https://github.com/PRQL/prql-vscode/assets/656833/0c06b69f-b6f9-4b19-b050-e04af534a7be)

Could be safe to close this for now.

**Comment by max-sixty** [comment]
Thanks @RandomFractals ! (and hope all is well!)
