### ISSUE TITLE
SQL Ouput color scheme

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [PRQL/prql-vscode#26]
It seems that values for the output are not well picked in some cases. For me all the keywords are black on black in the sql output for example.
adding screenshot currently does not work in github

**Comment by jiripospisil** [comment]
What's the theme? I think what's happening here is that the theme you're trying to use is not bundled with the syntax highlighting library. Unfortunately VS Code doesn't give extensions access to the current theme's syntax colors and so as a fallback we pick a color from around the UI that *mostly* matches the keywords. Except that for some themes it doesn't.

**Comment by jiripospisil** [comment]
There's not much we can do at this point - we need to wait for VS Code API to give us access to the color theme. Closing for now.

**Comment by sschneider-ihre-pvs** [comment]
https://marketplace.visualstudio.com/items?itemName=ceciljacob.code-plus-theme
Theme + Dark Blue Theme
