### ISSUE TITLE
SQL preview fails on Theme Change

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [PRQL/prql-vscode#27]
It seems to get stuck in loading when the color theme is changed

**Comment by jiripospisil** [comment]
Works for me. Does it happen every time?

https://user-images.githubusercontent.com/20820/210796587-0192fa86-a0da-485b-8213-bfe03d96f4ea.mp4

**Comment by jiripospisil** [comment]
Closing for now. Please reopen if you have reproduction steps. Thank you!
