### ISSUE TITLE
VS Code extension shows 0.9.1

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql-vscode#278]
Using VS Code (up to date) on a Mac, I note that the VS Code extension for PRQL has the version number in its documentation of 0.9.2. But the code it generates from `from invoices` shows a version comment of 0.9.1:

```
SELECT
  *
FROM
  invoices

-- Generated by PRQL compiler version:0.9.1 (https://prql-lang.org)
```

**Comment by eitsupi** [comment]
https://github.com/PRQL/prql-vscode/releases/tag/0.9.2 doesn't contain prql-js 0.9.2.
I think @max-sixty has misnamed the tag.

**Comment by max-sixty** [comment]
Sorry! That was not my best day.

I think this is fine to leave until the next release though — there's no actual difference in the code.

**Comment by richb-hanover** [comment]
I agree it's OK to leave. How shall we remember to do this when the next release comes out? Leave this issue open?

**Comment by max-sixty** [comment]
Best way is probably dependabot, which does it automatically...
