### ISSUE TITLE
Rename PRQL - SQL Output panel to SQL Preview

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#46]
and use standard vscode `$(open-preview)` icon with `SQL Preview` webview panel title to display generated SQL code.

This would ensure we are using standard vscode icon and nomenclature for the Preview panel.

The corresponding command id would change to `prql.openSqlPreview`. Most extensions use ext. name as namespace, `.` for the command, view, or setting name separator and camel case for the names of those objects.

Below is the demo of new SQL Preview command, icon and Preview display. We can drop PRQL part from the preview panel title because it's clear that the panel is created by the PRQL extension as indicated by the panel icon in its titlebar.

Let's decide on what Create SQL Document or Compile to SQL and Run should look like in #42.

The proposed changes below should take care of standardizing auto-updated SQL Preview.

![prql-sql-preview](https://user-images.githubusercontent.com/656833/216770510-245b1565-15f3-4458-ba30-a97954a7c6f7.gif)

**Comment by max-sixty** [comment]
Closing from #47. Excellent idea!
