### ISSUE TITLE
Table col name auto-completion?

### ISSUE THREAD

**Issue by futu2** [PRQL/prql-vscode#525]
for table which type defined in default_db, it is ok to check if table.col1 is valid.
However, auto -completion is not available.
e.g.
```prql
module default_db {
type tableType = [{c1 = text, c2 = text}]
let table1<tableType>
}
from table1
select {
  test = table1.xxx
}
```

**Comment by max-sixty** [comment]
Yes, this is something we *really* want to add, but we're not there yet in the compiler. We're currently rewriting the resolver, so this sort of thing will come after that. Check out https://prql-lang.org/roadmap/ for more...
