### ISSUE TITLE
Add VSCode marketplace badges to README.md

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#87]
We can use shields.io to display PRQL extension version, number of installs, downloads and extension rating.

Enter `PRQL-lang.prql-vscode` in the `Item Name` field on this badges web page to preview current RPQL vscode extension stats: 

https://vsmarketplacebadges.dev/

![prql-vscode-badges-preview](https://user-images.githubusercontent.com/656833/218758179-a67621c3-dcb5-45b1-aba2-0313c20976f0.png)

Recommended badges to display and add to this extension README.md from the preview form above:

- Version (Short)
- Installs
- Downloads
- Rating (Short)

As noted in prql discord integrations channel, Downloads badge displays all extension downloads and helps to see the number of users retaining and updating PRQL extension between different published versions.

Learn more about VSCode marketplace badges at: https://code.visualstudio.com/api/references/extension-manifest#approved-badges

**Comment by snth** [comment]
Getting some visibility on the number of downloads and installs would be great!

I am in favour of this.

**Comment by RandomFractals** [comment]
Great! I'll PR it today.

**Comment by max-sixty** [comment]
Definitely!

**Comment by RandomFractals** [comment]
Example of how that shows up from duckdb ext:

![image](https://user-images.githubusercontent.com/656833/218838815-198bc5ab-8ffb-4016-835e-0e7733f46497.png)

**Comment by RandomFractals** [comment]
See new badges in docs: https://github.com/PRQL/prql-vscode#prql-extension-for-visual-studio-code
