### ISSUE TITLE
Create PRQL to PostgreSQL demo data and sample queries to add to new Integrations section in README.md

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#88]
Maybe even create an example with scan of PostgreSQL data into duckdb using this [scanner](https://duckdb.org/2022/09/30/postgres-scanner.html) duckdb extension and demo it with PRQL vscode extension, [SQLTools](https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools), [PostgreSQL Driver](https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools-driver-pg) and [DuckDB SqlTools](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.duckdb-sql-tools).

**Comment by snth** [comment]
Happy to be subscribed to this issue but I doubt I'll be able to help with recording a demo gif any time soon.

With your velocity @RandomFractals I'm sure you'll get there before me.

**Comment by RandomFractals** [comment]
@snth I can cut the gif. Demo data/db prep and scripting is usually the most time consuming part as you know.

I assigned it for both of us to tackle this and review when we find time for it.
