### ISSUE TITLE
Add PRQL Settings shortcut menu button to SQL Preview and PRQL Editor titlebar

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#90]
for quick toggles of PRQL target setting added in #63 and other new/future PRQL configuration settings display.

I've only played with sqlite and duckdb with prql so far, but found myself keeping vscode Settings tab open when switching between my demo dbs to generate diff. sql outputs.

We could use the standard vscode cog/config icon for quick access to those PRQL Settings. 

Also, while at it, do we need to add more PRQL compiler toggles/settings?

Quick example of the Settings shortcut from our old Snippets Viewer for the general idea. Clicking on the cog icon in snippets tree view takes you directly to extension config. settings in this example:

![snippets-viewer-tree-view](https://user-images.githubusercontent.com/656833/218841157-dd599b00-e492-40d4-8759-09917643e920.png)

**Comment by RandomFractals** [comment]
One note: when the one and only PRQL Target setting changes when this shortcut menu is added, we'll refresh SQL Preview to generate SQL output for the selected SQL target system. Currently, you have to close & reopen SQL Preview to see new target system sql output.

**Comment by RandomFractals** [comment]
Looking at the current JS lib `CompilerOptions`, the only other prql setting that might be worth exposing in ext. config is `signature comment` that adds prql compiler signature with version and `target` for the generated SQL.

I can see how some users might not want to have that comment added to the generated SQL files.

CompilerOptions: https://github.com/PRQL/prql/blob/main/prql-js/src/lib.rs#L46

**Comment by RandomFractals** [comment]
See how it works in updated config section in docs: https://github.com/PRQL/prql-vscode#configuration

**Comment by max-sixty** [comment]
Looking good @RandomFractals !
