### ISSUE TITLE
Add PRQL compiler signature comment boolean setting to extension config

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#94]
Looking at the current JS lib `CompilerOptions`, the only other prql setting that might be worth exposing in ext. config is `signature comment` that adds prql compiler signature with version and `target` for the generated SQL.

I can see how some users might not want to have that comment added to the generated SQL files.

CompilerOptions: https://github.com/PRQL/prql/blob/main/prql-js/src/lib.rs#L46

_Originally posted by @RandomFractals in https://github.com/PRQL/prql-vscode/issues/90#issuecomment-1431238312_

**Comment by RandomFractals** [comment]
New `prql.addCompilerSignatureComment` setting display and sql preview output without the `Generated by` compiler comment:

![prql-add-compiler-signature-comment-setting](https://user-images.githubusercontent.com/656833/219077800-f31e3220-d124-4226-a9b6-210edb576de9.png)

**Comment by max-sixty** [comment]
Nice!
