### ISSUE TITLE
Change prql.target extension setting default to Generic and add None option

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql-vscode#98]
Currently the default target setting is Ansi. 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/5635139/219109916-20bea1e2-878d-4ed4-9348-0c1b216fce14.png">

My mental model is that it should be `None`, since if we start turning on warnings / errors where this value is different from the value in the query header, they would almost always be triggered with the current approach

**Comment by RandomFractals** [comment]
I was looking at that today too as I was checking exposed `CompileOptions`.

We set the default to `Ansi` as the first and most likely more standard SQL target option.

Do we mean this by Ansi SQL? https://blog.ansi.org/2018/10/sql-standard-iso-iec-9075-2016-ansi-x3-135/

In any case, when using PRQL with different database systems, expectations are you'd set the target to what flavor of SQL to output.

It might be confusing to have `None`. Does that mean no SQL output is generated?

The other option we have is `generic`. Also, not clear what that represents. Is it the same as `Ansi`?

**Comment by max-sixty** [comment]
> It might be confusing to have `None`. Does that mean no SQL output is generated?

Yes, good point. 

Ideally, we want an option which is "defer to the query"; so far that's been `None`. Currently, when `None` is passed to the function, and there's no text in the query header, we default to generic SQL. In the future, I guess that might be presumptuous if we were to we compile to more than SQL.

Ref https://github.com/PRQL/prql/issues/1686.

> The other option we have is `Generic`. Also, not clear what that represents. Is it the same as `Ansi`?

They are functionally the same at the moment; I definitely agree `Generic` is better than `Ansi`, since it's closer to None.

The issue will come if we turn on warnings / errors on the values being different — they'd get triggered anytime someone supplied `target:sql.postgres`, because the compiler would see `Generic` was passed.

Some options:
- Default to Generic, resolve how we handle disagreements between the function arg and the query header later (e.g. we could not warn on Generic, but then there's a special-case)
- Default to None, resolve whether that's presumptuous in the distant future

WDYT @RandomFractals ?

**Comment by RandomFractals** [comment]
@max-sixty & @aljazerzen I propose we do the following to provide an option that lets users overwrite prql target in `.prql` file with `None`:

- Add `None` to `prql.target` enum in extension settings config in `package.json`
- Document what that option means in new prql settings md table we'll add in #97
- Provide a link to [`prql target:sql.<dialect>`](https://prql-lang.org/book/language-features/target.html) documentation page from PRQL Book that contains examples of setting sql target and system dialect in prql file header
- Skip setting and passing `target` option in `CompileOptions` when ext. `prql.target` setting is `None`
- Default `prql.target` setting to `Generic` as that is the current prql compiler default too.

These changes would allow users to specify and use `prql target` header in `.prql` files and ignore extension `prql.target` setting in such cases.

I would suggest the ambiguity and difference between `Ansi` and `Generic` SQL flavor targets is documented on PRQL book [`target`](https://prql-lang.org/book/language-features/target.html) documentation page. Most users would probably know, can guess, or search to learn more about what Ansi SQL means, and might be thrown off by the `Generic` option. Why I set it to `Ansi` default in the initial version of this new extension `prql.target` setting feature implementation.

**Comment by eitsupi** [comment]
My understanding is that this has to do with prql-js default values.
Currently the default is `"sql.generic"`.
https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-js/src/lib.rs#L106

I noticed this in PRQL/prql#1750, but left the default as Generic to let it pass existing test cases.
https://github.com/PRQL/prql/pull/1750/commits/0ba1b23fcd32a1c418607a086def9ce6aa00238e

BTW, in prqlr, it is `None`.
https://github.com/eitsupi/prqlr/blob/a4ceb55bb02bbf7813482b6ce764dfc3aed12f38/src/rust/src/lib.rs#L21

**Comment by RandomFractals** [comment]
@eitsupi that's good to know. I still think either `Generic` or `Ansi` as a more standard option default would make sense.

We'll add `None` option so that users can specify their target in prql file header. However, I don't think we should be passing that target option to our compile call with prql-js, and the compiler should just produce "generic" sql or check prql target header in the file.

**Comment by RandomFractals** [comment]
I would even argue that if we default to `Generic` and there is `prql target:sql.sqlite` set in the prql query file, PRQL compiler should generate SQLite flavor of that query, i.e. same as what `None` currently does per your definition of it in the core lib.

**Comment by eitsupi** [comment]
Only `None` falls back to the header.
if there is nothing in the header after falling back from `None` to the header, it falls back to `Gneric`.

https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-compiler/src/sql/gen_query.rs#L26-L36
https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-compiler/src/sql/dialect.rs#L89-L93

So basically the default should be `None` in bindings.

**Comment by eitsupi** [comment]
I created a issue about that PRQL/prql#1855

**Comment by RandomFractals** [comment]
@eitsupi well, looking at `prql-js` tests, that `None` option can be any value not in the supported `sql.*` dialects list?

I found `opts.target = "sql.not_existing";` in https://github.com/PRQL/prql/blob/main/prql-js/tests/test_all.js#L75

Should be `sql.none` or `none` instead?

Please document it in `prql-js` lib docs: https://github.com/PRQL/prql/blob/main/prql-js/README.md

**Comment by eitsupi** [comment]
@RandomFractals I think the only way to set it to `None` from the JS side at the moment is by not passing anything to the CompileOptions.
https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-js/src/lib.rs#L104-L114

If nothing is passed, Target will be `Sql(None)`.
https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-compiler/src/lib.rs#L138-L142

So, we need to change the default value of prql-js, I create a PR.

**Comment by RandomFractals** [comment]
ok. this seems to work. I'd rather set default to `Generic` and will pass `sql.none` for the None option which is ignored by the prql-js compiler v0.5.0 and produces "generic" sql too, if no `prql target:sql.*` dialiect setting is found in the `.prql` file header. See: https://github.com/PRQL/prql-vscode/commit/9e9626a929b01c56c7a6b94e90164d99a9a5ebd2

tbh, I wish those options were better documented in `prql-js` docs for the users of that JS library.

**Comment by RandomFractals** [comment]
> @RandomFractals I think the only way to set it to `None` from the JS side at the moment is by not passing anything to the CompileOptions. https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-js/src/lib.rs#L104-L114
> 
> If nothing is passed, Target will be `Sql(None)`. https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-compiler/src/lib.rs#L138-L142
> 
> So, we need to change the default value of prql-js, I create a PR.

Please link to lines in main instead next time.

I tested the above and when I don't pass `sql.none` target in `CompileOptions` the `prql target:...` header in `.prql` file is ignored. 🤷

**Comment by RandomFractals** [comment]
> So, we need to change the default value of prql-js, I create a PR.

I think we should keep the "generic" default as is. I going to write up and submit my PR for this change shortly.

Defaults to Generic, adds None, generates "generic" sql or whatever is in `prql target` header.

**Comment by eitsupi** [comment]
> Please link to lines in main instead next time.

These are main. They are just permalinks.

> I tested the above and when I don't pass `sql.none` target in `CompileOptions` the `prql target:...` header in `.prql` file is ignored. 🤷

Oh, perhaps that behavior has been changed in the current main. (maybe 0.5.1?)

**Comment by eitsupi** [comment]
I was talking about the main branch (changed after 0.5.0).
As I understand it, there is currently no way to set it to `Sql(None)` to Target other than not passing CompileOptions in prql-js.

I believe we can solve this in the following two ways.

- Set default value to `Sql(None)` (https://github.com/PRQL/prql-vscode/issues/98#issuecomment-1432921411)
- Set a special value here that will be converted to `Sql(None)`. https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-compiler/src/lib.rs#L153-L172

**Comment by RandomFractals** [comment]
@eitsupi per above and changes I am about to PR from [`prql-target-default`](https://github.com/PRQL/prql-vscode/tree/prql-target-default) branch, vscode extension will default to `Generic` and have new `None` options users can use. I still think that that default should be `Ansi` as most folks know what ANSI SQL is, and "generic" needs to be defined somewhere. However, for the time being I think the changes I am going to PR give you the behavior you prefer. 

Let me wrap up those changes and cut a gif to demo them so we have some visuals to discuss it further, if needed.

**Comment by RandomFractals** [comment]
> As I understand it, there is currently no way to set it to `Sql(None)` to Target other than not passing CompileOptions in prql-js.

@eitsupi you might be right about this. I merged my PR and did try both passing `sql.none`, `none`, and not passing the target option, but I always get generic sql back without saying it is generic in compiler signature comment, and it ignores prql target set in file header.

So, the best I can do is probably try skipping options completely when a user selects None.

**Comment by RandomFractals** [comment]
not passing compile options does not help either. so, we might need a fix in prql-js lib for this to work, or better docs on what I should be passing to `compile()` for the None option. cc @aljazerzen 

Last bit I tried:

```typescript
...
  let compileOptions = undefined;
  if (target !== 'None') {
    // create compile options from prql workspace settings
    compileOptions = new prql.CompileOptions();
    compileOptions.target = `sql.${target.toLowerCase()}`;
    compileOptions.signature_comment = addCompilerInfo;
  }
...
```

**Comment by eitsupi** [comment]
@RandomFractals I created PR for that. PRQL/prql#1856
Make sure new test cases cover the use cases here.

**Comment by RandomFractals** [comment]
@eitsupi well, sounds like you really want the 'None' default. I don't agree with that option at all, but will if everyone else feels the same. 

Let me know when that change is in and `prql-js` lib is updated and published for us to use it.

Thanks for looking into this too!

**Comment by aljazerzen** [comment]
I agree with @eitsupi in that we need a "None" or "Unset" or "Fallback to prql header" option that translates to:

```js
const opts = new CompileOptions()
opts.target = null;
...
```

(I would even say that this should be the default, but I'm not willing to argue on that).

**Comment by RandomFractals** [comment]
ok. Just to clarify:

- `None` was added
- `Generic` is the default in vscode extension now
- I'll document those parts in docs in #97 

Remaining: for `prql-js` to support `options.target === null || undefined || 'none'`

I'll wait for that lib to get updated to finish the rest here.

**Comment by max-sixty** [comment]
(FWIW agree with this direction — allowing or defaulting to `None` is `prql-js`, which would allow the query to define the dialect)

**Comment by RandomFractals** [comment]
Great! still blocked and waiting for the `prql-js` v0.5.1 release with the patches in the core prql compiler lib to finalize this feature.

> Remaining: for `prql-js` to support `options.target === null || undefined || 'none'`

**Comment by max-sixty** [comment]
> Great! still blocked and waiting for the `prql-js` v0.5.1 release with the patches in the core prql compiler lib to finalize this feature.

Released!

**Comment by RandomFractals** [comment]
Not sure why our compile.ts can't find it. I do see it published and npm install update worked just fine after bumping it in package.json ...

![image](https://user-images.githubusercontent.com/656833/219856806-7b90e734-65de-4032-9ce0-089aa8bc8f27.png)

**Comment by RandomFractals** [comment]
@max-sixty this is what I see in /node_modules after update to prql-js v0.5.1:

![image](https://user-images.githubusercontent.com/656833/219857153-cc30e05e-1aea-4023-8512-1dd5d7cba6ae.png)

i.e. no js in that published module. Might need another repackage and publish to npmjs.

**Comment by eitsupi** [comment]
We can confirm it in the logs.

0.5.0
https://github.com/PRQL/prql/actions/runs/4130439718/jobs/7137127192#step:4:1
0.5.1
https://github.com/PRQL/prql/actions/runs/4207097290/jobs/7301452313#step:4:1

I'm not sure what happened with 0.5.1 because the build steps look the same......

**Comment by RandomFractals** [comment]
sounds like prql-js bundling has been fixed in https://github.com/PRQL/prql/pull/1887

**Comment by RandomFractals** [comment]
@max-sixty still not sure if `prql-js` v0.5.2 actually generates sql for the requested target in prql file header.

I am going to close this as default to Generic target update is done and I added None option.

@eitsupi & @aljazerzen might need to push another `prql-js` `CompileOptions.target` fix for the rest to work.

![image](https://user-images.githubusercontent.com/656833/219976057-00ba7650-7a04-4ec3-8adb-cb6f9078fa98.png)

**Comment by aljazerzen** [comment]
Try

```
prql target:sql.mssql

...
```
... and check if `take` is compiled to `TOP`.

(target is not emitted in the signature if CompileOptions.target is not set)

**Comment by RandomFractals** [comment]
yep. that works. So, I guess `None` option is good to go now too. 

![image](https://user-images.githubusercontent.com/656833/219976864-2e20cd34-afa6-483e-b242-8c91eacba1bc.png)

I'll doc the rest and will publish new release tomorrow.
