### ISSUE TITLE
Set PRQL Settings order to show Target setting first

### ISSUE THREAD

**Issue by RandomFractals** [PRQL/prql-vscode#99]
VSCode extension configuration properties now support `order` field to overwrite the default alphabetical order of settings display.

We'll add `order: 0` to target and `order: 1` to new compiler signature comment toggle setting to display PRQL Target setting first.

Then PRQL Settings will show up as following:

![image](https://user-images.githubusercontent.com/656833/219167015-e11f633a-4b8f-44f4-8630-c5632c0fe4f5.png)

**Comment by max-sixty** [comment]
Great, agree!
